# Generated by Django 4.1.2 on 2023-03-11 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=127, unique=True)),
                ('password', models.CharField(max_length=63)),
                ('dateCreated', models.DateField(default=datetime.datetime.utcnow, editable=False)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.stock')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('nid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('news', models.TextField()),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField(blank=True, default=0, null=True)),
                ('close', models.FloatField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stock')),
            ],
        ),
    ]
