# Generated by Django 4.1.2 on 2023-01-12 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=63)),
                ('close', models.FloatField()),
                ('predicted_close', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=127, unique=True)),
                ('password', models.CharField(max_length=63)),
                ('dateCreated', models.DateField(default=datetime.datetime.utcnow, editable=False)),
                ('stock_id_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('news', models.TextField()),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('stock_idn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('stock_idh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stocks')),
            ],
        ),
    ]
