# Generated by Django 4.1.7 on 2023-04-22 08:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='high',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='low',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='volume',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sentiment_model', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=5)),
                ('historical_model', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=5)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stock')),
            ],
        ),
    ]
