# Generated by Django 4.1.2 on 2023-02-04 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_news_date_remove_news_stock_idn'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('news_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('news', models.TextField()),
                ('sentiment', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='stock_id_1',
            new_name='stock',
        ),
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stock',
        ),
        migrations.AddField(
            model_name='new',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stock'),
        ),
    ]
