# Generated by Django 4.1.2 on 2023-02-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_new_rename_users_user_delete_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.stock'),
        ),
    ]
