# Generated by Django 4.1.2 on 2023-02-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_new_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='stock_idh',
            new_name='stock',
        ),
    ]
